# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d69178094cd170a75a726f1b6335ffb77e527f07dc4c121522fc422f47886e9e3827e1859a773c1663bc0034aeac777fd254fe1f74e2a49b8e5d42504d50838

test:
  secret_key_base: 4ee9d90c90b523dd925e8e1f48d03e8615962351c792d8cffa1fe168d66827690a5879b42e384a3f2e5dc6f715481e16fff8d7f21da9aaa163400e376ae6eefb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
